// login 
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REQ_SUCCESS = 'REQ_SUCCESS';
export const RESET_SUCCESS = 'RESET_SUCCESS';

// sign up
export const NEXT_SCREEN = 'NEXT_SCREEN';
export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

//profile
export const PROFILE_REQUESTED = 'PROFILE_REQUESTED';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_ERROR = 'PROFILE_ERROR';

//profile
export const BILL_REQUESTED = 'BILL_REQUESTED';
export const BILL_SUCCESS = 'BILL_SUCCESS';
export const BILL_ERROR = 'BILL_ERROR';


//profile
export const COMPANY_REQUESTED = 'COMPANY_REQUESTED';
export const COMPANY_SUCCESS = 'COMPANY_SUCCESS';
export const COMPANY_ERROR = 'COMPANY_ERROR';
export const COMPANY_ADDED = 'COMPANY_ADDED';
export const COMPANY_ADDED_REMOVE = 'COMPANY_ADDED_REMOVE';


//workspace
export const WORKSPACE_REQUESTED = 'WORKSPACE_REQUESTED';
export const WORKSPACE_SUCCESS = 'WORKSPACE_SUCCESS';
export const WORKSPACE_ERROR = 'WORKSPACE_ERROR';
export const WORKSPACE_CATEGORY = 'WORKSPACE_CATEGORY';
export const ADD_WORKSPACE_SUCCESS = 'ADD_WORKSPACE_SUCCESS';
export const REMOVE_WORKSPACE_SUCCESS = 'REMOVE_WORKSPACE_SUCCESS';
export const UPLOAD_IMAGE_REQUESTED = 'UPLOAD_IMAGE_REQUESTED';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';

//event
export const EVENT_REQUESTED = 'EVENT_REQUESTED';
export const EVENT_SUCCESS = 'EVENT_SUCCESS';
export const EVENT_ERROR = 'EVENT_ERROR';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_REQUESTED = 'ADD_EVENT_REQUESTED';
export const REMOVE_EVENT_SUCCESS = 'REMOVE_EVENT_SUCCESS';

export const FETCH_EVENT_PACKAGE_REQUESTED = 'FETCH_EVENT_PACKAGE_REQUESTED';
export const FETCH_EVENT_PACKAGE_SUCCESS = 'FETCH_EVENT_PACKAGE_SUCCESS';
export const FETCH_EVENT_PACKAGE_ERROR = 'FETCH_EVENT_PACKAGE_ERROR';

//location
export const LOCATION_REQUESTED = 'LOCATION_REQUESTED';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';
export const LOCATION_ERROR = 'LOCATION_ERROR';

//community
export const COMMUNITY_REQUESTED = 'COMMUNITY_REQUESTED';
export const COMMUNITY_SUCCESS = 'COMMUNITY_SUCCESS';
export const COMMUNITY_ERROR = 'COMMUNITY_ERROR';

//support 
export const SUPPORT_REQUESTED = 'SUPPORT_REQUESTED';
export const SUPPORT_SUCCESS = 'SUPPORT_SUCCESS';
export const SUPPORT_ERROR = 'SUPPORT_ERROR';

export const ADD_SUPPORT_REQUESTED = 'ADD_SUPPORT_REQUESTED';
export const ADD_SUPPORT_SUCCESS = 'ADD_SUPPORT_SUCCESS';
export const ADD_SUPPORT_ERROR = 'ADD_SUPPORT_ERROR';

export const ADD_SUPPORT_FEEDBACK_REQUESTED = 'ADD_SUPPORT_FEEDBACK_REQUESTED';
export const ADD_SUPPORT_FEEDBACK_SUCCESS = 'ADD_SUPPORT_FEEDBACK_SUCCESS';
export const ADD_SUPPORT_FEEDBACK_ERROR = 'ADD_SUPPORT_FEEDBACK_ERROR';

export const GET_TICKET_DETAIL_REQUESTED = 'GET_TICKET_DETAIL_REQUESTED';
export const GET_TICKET_DETAIL_SUCCESS = 'GET_TICKET_DETAIL_SUCCESS';
export const GET_TICKET_DETAIL_ERROR = 'GET_TICKET_DETAIL_ERROR';

//Guest
export const GUEST_REQUESTED = 'GUEST_REQUESTED';
export const GUEST_SUCCESS = 'GUEST_SUCCESS';
export const GUEST_ERROR = 'GUEST_ERROR';

export const ADD_GUEST_REQUESTED = 'ADD_GUEST_REQUESTED';
export const ADD_GUEST_SUCCESS = 'ADD_GUEST_SUCCESS';
export const ADD_GUEST_ERROR = 'ADD_GUEST_ERROR';

export const EDIT_GUEST_REQUESTED = 'EDIT_GUEST_REQUESTED';
export const EDIT_GUEST_SUCCESS = 'EDIT_GUEST_SUCCESS';
export const EDIT_GUEST_ERROR = 'EDIT_GUEST_ERROR';

export const DELETE_GUEST_REQUESTED = 'DELETE_GUEST_REQUESTED';
export const DELETE_GUEST_SUCCESS = 'DELETE_GUEST_SUCCESS';
export const DELETE_GUEST_ERROR = 'DELETE_GUEST_ERROR';

export const ADD_MEETUP_SESSION_REQUEST = 'ADD_MEETUP_SESSION_REQUEST';
export const ADD_MEETUP_SESSION_SUCCESS = 'ADD_MEETUP_SESSION_SUCCESS';
export const ADD_MEETUP_SESSION_ERROR = 'ADD_MEETUP_SESSION_ERROR';

export const MEETUP_SESSION_REQUESTED = 'MEETUP_SESSION_REQUESTED';
export const MEETUP_SESSION_SUCCESS = 'MEETUP_SESSION_SUCCESS';
export const MEETUP_SESSION_ERROR = 'MEETUP_SESSION_ERROR';

export const EDIT_MEETUP_SESSION_REQUESTED = 'EDIT_MEETUP_SESSION_REQUESTED';
export const EDIT_MEETUP_SESSION_SUCCESS = 'EDIT_MEETUP_SESSION_SUCCESS';
export const EDIT_MEETUP_SESSION_ERROR = 'EDIT_MEETUP_SESSION_ERROR';

export const SELECT_MEETUP_SESSION = 'SELECT_MEETUP_SESSION';

export const GET_SINGLE_MEETUP_SESSION = 'GET_SINGLE_MEETUP_SESSION'
export const GET_SINGLE_MEETUP_SUCCESS = 'GET_SINGLE_MEETUP_SUCCESS'
export const GET_SINGLE_MEETUP_ERROR = 'GET_SINGLE_MEETUP_ERROR'

export const DELETE_MEETUP_SESSION_REQUESTED = 'DELETE_MEETUP_SESSION_REQUESTED'
export const DELETE_MEETUP_SESSION_SUCCESS = 'DELETE_MEETUP_SESSION_SUCCESS'
export const DELETE_MEETUP_SESSION_ERROR = 'DELETE_MEETUP_SESSION_ERROR'

//Blueface
export const BF_REQUESTED = 'BF_REQUESTED';
export const BF_SUCCESS = 'BF_SUCCESS';
export const BF_ERROR = 'BF_ERROR';
export const BF_COMMETS = 'BF_COMMETS';
export const BF_COMMET_ADDED = 'BF_COMMET_ADDED';
export const BF_REMOVE_SUCCESS = 'BF_REMOVE_SUCCESS';

//Notification
export const NOTIF_REQUESTED = 'NOTIF_REQUESTED';
export const NOTIF_SUCCESS = 'NOTIF_SUCCESS';
export const NOTIF_ERROR = 'NOTIF_ERROR ';

//Services
export const SERVICES_REQUESTED = 'SERVICES_REQUESTED';
export const SERVICES_SUCCESS = 'SERVICES_SUCCESS';
export const SERVICES_ERROR = 'SERVICES_ERROR';
export const SERVICES_CATEGORY = 'SERVICES_CATEGORY';

//Tour
export const TOUR_REQUESTED = 'TOUR_REQUESTED';
export const TOUR_SUCCESS = 'TOUR_SUCCESS';
export const TOUR_ERROR = 'TOUR_ERROR';